name: Build and Publish Docker Image

on:
  push:
    branches:
      - unstable
    tags:
      - '[0-9]+\.[0-9]+\.[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: docker/setup-qemu-action@v2

      - uses: docker/setup-buildx-action@v2

      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Set image tags
        id: set-tags
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            TAG=${GITHUB_REF#refs/tags/}
            echo "tags=ghcr.io/panonim/qbwrapper:${TAG},ghcr.io/${{ github.repository_owner }}/qbwrapper:latest" >> $GITHUB_OUTPUT
          elif [[ "${GITHUB_REF}" == refs/heads/unstable ]]; then
            echo "tags=ghcr.io/panonim/qbwrapper:unstable-${GITHUB_RUN_NUMBER}" >> $GITHUB_OUTPUT
          else
            echo "tags=" >> $GITHUB_OUTPUT
          fi

      - name: Build and push Docker image
        if: steps.set-tags.outputs.tags != ''
        uses: docker/build-push-action@v4
        with:
          context: ./app
          file: ./app/Dockerfile
          push: true
          tags: ${{ steps.set-tags.outputs.tags }}
