name: Build and Publish Docker Image

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
    branches:
      - unstable

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: docker/setup-qemu-action@v2

      - uses: docker/setup-buildx-action@v2

      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./app
          file: ./app/Dockerfile
          push: true
          tags: ${{ steps.set-tags.outputs.tags }}

    outputs:
      image-tags: ${{ steps.set-tags.outputs.tags }}

  set-tags:
    runs-on: ubuntu-latest
    outputs:
      tags: ${{ steps.set-tags.outputs.tags }}
    steps:
      - id: set-tags
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            TAG=${GITHUB_REF#refs/tags/}
            echo "tags=ghcr.io/${GITHUB_REPOSITORY_OWNER}/qbwrapper:${TAG},ghcr.io/${GITHUB_REPOSITORY_OWNER}/qbwrapper:latest" >> $GITHUB_OUTPUT
          elif [[ "${GITHUB_REF}" == refs/heads/unstable ]]; then
            echo "tags=ghcr.io/${GITHUB_REPOSITORY_OWNER}/qbwrapper:unstable-${GITHUB_RUN_NUMBER}" >> $GITHUB_OUTPUT
          else
            echo "tags=" >> $GITHUB_OUTPUT
          fi
